"""
runner.py

Runs a 2D OpenFOAM case using Docker.

The script is used by the KBE application after a 2D OpenFOAM case has
already been generated by ``case_generator.py``. It can also be run manually
from WSL / Ubuntu for testing.
"""

import os
import sys
import subprocess
from pathlib import Path

# -----------------------------------------------------------------------------
# Docker and case selection settings
# -----------------------------------------------------------------------------
DOCKER_IMAGE = "opencfd/openfoam-default:2206"
DEFAULT_CASE_NAME = "case_004_slope_jet_bed_slope_large_2d"


if len(sys.argv) > 1:
    CASE_NAME = sys.argv[1]
else:
    CASE_NAME = os.environ.get("OPENFOAM_CASE_NAME", DEFAULT_CASE_NAME)

# -----------------------------------------------------------------------------
# Functions used to locate the project and selected OpenFOAM case
# -----------------------------------------------------------------------------

def armourstone_folder():
    """Return the ArmourStone folder."""
    return Path(__file__).resolve().parents[1]


def case_folder():
    """Return the OpenFOAM case folder."""
    return armourstone_folder() / "cases" / CASE_NAME

# -----------------------------------------------------------------------------
# Function used to run OpenFOAM inside Docker
# -----------------------------------------------------------------------------

def run_openfoam():
    """Run blockMesh, checkMesh, topoSet, simpleFoam and write cell centres."""

    root = armourstone_folder()
    case_dir = case_folder()

    if not case_dir.exists():
        raise FileNotFoundError(
            f"Case folder not found:\n{case_dir}\n\n"
            "Run case_generator.py first."
        )

    docker_case_dir = f"/work/cases/{CASE_NAME}"

    commands_inside_docker = f"""
cd {docker_case_dir}

echo "Running blockMesh..."
blockMesh > log.blockMesh 2>&1

echo "Running checkMesh..."
checkMesh > log.checkMesh 2>&1

echo "Running topoSet..."
topoSet > log.topoSet 2>&1

echo "Running simpleFoam..."
simpleFoam > log.simpleFoam 2>&1

echo "Writing cell centres..."
postProcess -func writeCellCentres -latestTime > log.writeCellCentres 2>&1 || true

echo "Creating ParaView file..."
touch {CASE_NAME}.foam

echo "Done."
"""

    docker_command = [
        "docker",
        "run",
        "--rm",
        "-v",
        f"{root}:/work",
        DOCKER_IMAGE,
        "bash",
        "-lc",
        commands_inside_docker,
    ]

    result = subprocess.run(
        docker_command,
        cwd=root,
        text=True,
        capture_output=True,
    )

    print(result.stdout)

    if result.returncode != 0:
        print(result.stderr)
        print_log_tail("log.blockMesh", 80)
        print_log_tail("log.checkMesh", 80)
        print_log_tail("log.topoSet", 80)
        print_log_tail("log.simpleFoam", 120)
        raise RuntimeError("OpenFOAM run failed. Check the log files.")

    print()
    print("OpenFOAM finished successfully.")
    print(f"Case name:   {CASE_NAME}")
    print(f"Case folder: {case_dir}")
    print(f"ParaView file: {case_dir / (CASE_NAME + '.foam')}")


def print_log_tail(log_name, n_lines=40):
    """Print the last lines of a log file."""

    path = case_folder() / log_name

    if not path.exists():
        print(f"Log file not found: {path}")
        return

    lines = path.read_text(errors="ignore").splitlines()

    print(f"\n--- Last {n_lines} lines of {log_name} ---")
    for line in lines[-n_lines:]:
        print(line)


if __name__ == "__main__":
    run_openfoam()

    print_log_tail("log.checkMesh")
    print_log_tail("log.simpleFoam")